//if lacks it results with "Instance is not associated with a key pair"

resource "aws_key_pair" "key_pair" {
  public_key = var.public_key //generated by ssh-keygen -y -f  parth to key-pair.file test-key-pair.pem
}
